# This must be the first line
import pandas as pd
pd.options.mode.copy_on_write = True

import matplotlib.figure as matplotlib_figure
import matplotlib.ticker as matplotlib_ticker
import numpy as np
import os
import streamlit as st

import glb
import romz_ampl
import romz_excel
import sbar
import report_ampl
import report_experts
import report_problem
import report_stats
import report_summary
import report_tasks



def show_main_panel():
    report_problem.show()
    report_summary.show()
    report_experts.show()
    report_tasks.show()
    report_stats.show()
    report_ampl.show()


def set_page_config():
    st.set_page_config(page_title="Yumbo",layout="wide")
    # css = '''
    # <style>
    #     [data-testid="stSidebar"]{
    #         min-width: 400px;
    #         max-width: 800px;
    #     }
    # </style>
    # '''
    # st.html(css)


def show_page_header():
    st.title(":red[Yumbo.] Scheduling, Planning and Resource Allocation")
    st.subheader("Zbigniew Romanowski, Paweł Koczyk")
    st.markdown("Source code, documentation and sample Excel input files can be found on [Yumbo's](https://github.com/romz-pl/yambo) GitHub repository.")
    st.caption(f"git hash: :green[{glb.get_git_hash()}]")
    st.caption("_{d}_".format(d=pd.Timestamp.now().strftime("%d %B %Y, %H:%M:%S %p")))


def show_yumbo_description():
    st.divider()
    cols = st.columns(2)

    # The cols[1] and cols[2] are not used!
    with cols[0]:
        dd = os.path.dirname(__file__)
        with open(f"{dd}/../doc/yumbo.md", "r") as f:
            st.markdown(f'''{f.read()}''')

    st.divider()
    st.image(f"{dd}/../doc/yumbo.webp")
    st.caption("Image generated by ChatGPT")


def init_sesion__stats():
    if 'stats' not in st.session_state:
        st.session_state.stats = dict()


    #
    # Stats must be zeroing for each execution of the program
    #

    # Take the session variable
    stats = st.session_state.stats

    charts = ["imgb", "imgg", "imggsum", "imgh", "imghsum", "imgs", "imgt", "imgtsum", "imgw", "imge"]
    for v in charts:
        stats[f"{v}:cnt"] = 0
        stats[f"{v}:ttime"] = 0
        stats[f"{v}:nbytes"] = 0

    stats["ampl:ttime"] = 0
    stats["excel:ttime"] = 0
    stats["report_experts:ttime"] = 0
    stats["report_tasks:ttime"] = 0
    stats["report_summary:ttime"] = 0


def init_sesion_show():
    if 'show' not in st.session_state:
        st.session_state.show = dict()
        show = st.session_state.show
        show["ampl_solver_log"] = False
        show["ampl_data_file"] = False
        show["ampl_model_file"] = False
        show["stats_chart"] = True
        show["stats_execution"] = True
        show["problem"] = False
        show["experts_summary"] = False


def init_sesion_variables():
    if 'amplsol' not in st.session_state:
        st.session_state.amplsol = pd.DataFrame()

    if 'glb' not in st.session_state:
        st.session_state.glb = dict()

    if 'mprob' not in st.session_state:
        st.session_state.mprob = dict()

    init_sesion__stats()
    init_sesion_show()


def upload():
    with st.sidebar:
        uploaded_file = sbar.get_uploaded_file()
        if uploaded_file != None:
            romz_excel.load(uploaded_file)
            sbar.show()

    return uploaded_file != None


def solve_problem():
    try:
        romz_ampl.solve()
    except Exception as e:
        st.subheader(f":red[Exception during solving process.] {e}")
        report_ampl.show_ampl_data_file()
        return False

    return True


def main():
    set_page_config()

    init_sesion_variables()
    show_page_header()

    if not upload():
        show_yumbo_description()
        return


    if not solve_problem():
        return

    show_main_panel()


######################## CALL MAIN FUNCTION ##################

if __name__ == "__main__":
    main()

